import React, { useMemo, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import { Search, Plus, Download, Eye, Ban, CheckCircle2, AlertTriangle, Key } from 'lucide-react';
import { ATMPageHeader } from '@/shared/components/ATMPageHeader';
import { ATMCard } from '@/shared/ui/ATMCard';
import { ATMButton } from '@/shared/ui/ATMButton';
import { ATMBadge, StatusBadge } from '@/shared/ui/ATMBadge';
import { ATMTextField } from '@/shared/ui/ATMTextField';
import { ATMSelectField } from '@/shared/ui/ATMSelectField';
import { ATMModal } from '@/shared/ui/ATMModal';
import { ATMStatsCard } from '@/shared/ui/ATMStatsCard';
import { ATMTable } from '@/shared/components/ATMTable/ATMTable';
import type { ATMTableColumn, RowAction } from '@/shared/components/ATMTable/ATMTable';
import { formatDate } from '@/lib/utils/formatDate';
import type { RechargeToken } from '../types/token.types';
import type { TokenMetrics } from '../services/useTokens';

const TIER_OPTIONS = [
  { label: 'All Tiers', value: '' },
  { label: 'Basic', value: 'Basic' },
  { label: 'Standard', value: 'Standard' },
  { label: 'Advance', value: 'Advance' },
  { label: 'Premium', value: 'Premium' },
];

const STATUS_OPTIONS = [
  { label: 'All Statuses', value: '' },
  { label: 'Active', value: 'Active' },
  { label: 'Expired', value: 'Expired' },
  { label: 'Consumed', value: 'Consumed' },
  { label: 'Revoked', value: 'Revoked' },
];

const TIER_BADGE_VARIANT: Record<string, 'gray' | 'primary' | 'purple' | 'warning'> = {
  Basic: 'gray',
  Standard: 'primary',
  Advance: 'purple',
  Premium: 'warning',
};

interface TokenListProps {
  tokens: RechargeToken[];
  isLoading: boolean;
  isFetching: boolean;
  totalCount: number;
  page: number;
  pageSize: number;
  onPageChange: (p: number) => void;
  onPageSizeChange: (s: number) => void;
  search: string;
  onSearchChange: (val: string) => void;
  tierFilter: string;
  onTierFilterChange: (val: string) => void;
  statusFilter: string;
  onStatusFilterChange: (val: string) => void;
  dateFrom: string;
  onDateFromChange: (val: string) => void;
  dateTo: string;
  onDateToChange: (val: string) => void;
  revokeTarget: { id: string; merchantName: string } | null;
  onRevokeTargetChange: (val: { id: string; merchantName: string } | null) => void;
  revokeReason: string;
  onRevokeReasonChange: (val: string) => void;
  onRevoke: () => void;
  isRevoking: boolean;
  onExportCsv: () => void;
  metrics?: TokenMetrics;
}

export const TokenList: React.FC<TokenListProps> = ({
  tokens,
  isLoading,
  isFetching,
  totalCount,
  page,
  pageSize,
  onPageChange,
  onPageSizeChange,
  search,
  onSearchChange,
  tierFilter,
  onTierFilterChange,
  statusFilter,
  onStatusFilterChange,
  dateFrom,
  onDateFromChange,
  dateTo,
  onDateToChange,
  revokeTarget,
  onRevokeTargetChange,
  revokeReason,
  onRevokeReasonChange,
  onRevoke,
  isRevoking,
  onExportCsv,
  metrics,
}) => {
  const navigate = useNavigate();

  const columns: ATMTableColumn<RechargeToken>[] = useMemo(
    () => [
      {
        key: 'id',
        header: 'Token ID',
        renderCell: (val, row) => (
          <span className="font-mono text-xs font-bold text-gray-900 dark:text-gray-100" title={row.id}>
            {row.id.slice(0, 8)}...
          </span>
        ),
      },
      {
        key: 'merchantName',
        header: 'Merchant',
        renderCell: (val, row) => (
          <span className="text-sm font-semibold text-gray-900 dark:text-gray-100">
            {row.merchantName}
          </span>
        ),
      },
      {
        key: 'tier',
        header: 'Tier',
        renderCell: (val, row) => (
          <ATMBadge color={TIER_BADGE_VARIANT[row.tier] ?? 'gray'} label={row.tier} />
        ),
      },
      {
        key: 'validity',
        header: 'Validity',
        renderCell: (val, row) => (
          <span className="text-xs text-gray-600 dark:text-gray-400 font-medium">
            {formatDate(row.validFrom, 'short')} - {formatDate(row.validTo, 'short')}
          </span>
        ),
      },
      {
        key: 'generatedAt',
        header: 'Generated',
        renderCell: (val, row) => (
          <span className="text-xs text-gray-600 dark:text-gray-400 font-medium">
            {formatDate(row.generatedAt, 'short')}
          </span>
        ),
      },
      {
        key: 'generatedBy',
        header: 'Generated By',
        renderCell: (val, row) => (
          <span className="text-xs text-gray-700 dark:text-gray-300 font-medium">
            {row.generatedBy}
          </span>
        ),
      },
      {
        key: 'status',
        header: 'Status',
        renderCell: (val, row) => (
          <StatusBadge status={row.status} />
        ),
      },
    ],
    []
  );

  const rowActions = useCallback(
    (row: RechargeToken): RowAction<RechargeToken>[] => {
      const actions: RowAction<RechargeToken>[] = [
        {
          label: 'View',
          icon: Eye,
          onClick: (r) => navigate(`/tokens/${r.id}`),
        },
      ];
      if (row.status === 'Active') {
        actions.push({
          label: 'Revoke',
          icon: Ban,
          variant: 'danger',
          onClick: (r) => onRevokeTargetChange({ id: r.id, merchantName: r.merchantName }),
        });
      }
      return actions;
    },
    [navigate, onRevokeTargetChange]
  );

  return (
    <div className="flex flex-col h-full bg-zen-surface animate-in fade-in duration-500 overflow-hidden w-full">
      {/* Upper Header and Stats Block */}
      <div className="px-6 py-5 border-b border-gray-100 dark:border-gray-800 flex-shrink-0 bg-zen-surface">
        <ATMPageHeader
          title="Token History"
          subtitle="View and manage all generated Standalone activation and recharge tokens."
          icon={Key}
          action={{
            label: 'Generate Token',
            onClick: () => navigate('/tokens/generate'),
            icon: Plus,
          }}
        />

        {/* Stats Cards - Always visible, defaulting to zero/loading state */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mt-8 animate-in fade-in zoom-in duration-300">
          <ATMStatsCard
            label="Active Tokens"
            value={metrics ? metrics.totalActive : (isLoading ? '...' : 0)}
            icon={CheckCircle2}
            variant="emerald"
          />
          <ATMStatsCard
            label="Generated This Month"
            value={metrics ? metrics.generatedThisMonth : (isLoading ? '...' : 0)}
            icon={Plus}
            variant="accent"
          />
          <ATMStatsCard
            label="Expiring (30 days)"
            value={metrics ? metrics.expiringWithin30Days : (isLoading ? '...' : 0)}
            icon={AlertTriangle}
            variant="purple"
          />
          <ATMStatsCard
            label="Expired / Revoked"
            value={metrics ? (metrics.totalExpired + metrics.totalRevoked) : (isLoading ? '...' : 0)}
            icon={Ban}
            variant="rose"
          />
        </div>
      </div>

      {/* Scrollable body content */}
      <div className="flex-1 overflow-y-auto px-6 py-6 space-y-6 bg-slate-50/10 dark:bg-gray-900/10">
        {/* Filters Card */}
        <ATMCard title="Search & Filters" padding="md" className="shadow-sm border border-gray-100 dark:border-gray-800">
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-5">
            <ATMTextField
              name="search"
              placeholder="Search by token ID or merchant..."
              value={search}
              onChange={(e) => onSearchChange(e.target.value)}
              prefix={<Search size={16} />}
            />
            <ATMSelectField
              name="tierFilter"
              placeholder="All Tiers"
              options={TIER_OPTIONS}
              value={tierFilter || null}
              onChange={(val) => onTierFilterChange(val as string || '')}
            />
            <ATMSelectField
              name="statusFilter"
              placeholder="All Statuses"
              options={STATUS_OPTIONS}
              value={statusFilter || null}
              onChange={(val) => onStatusFilterChange(val as string || '')}
            />
            <ATMTextField
              name="dateFrom"
              type="date"
              placeholder="From date"
              value={dateFrom}
              onChange={(e) => onDateFromChange(e.target.value)}
            />
            <ATMTextField
              name="dateTo"
              type="date"
              placeholder="To date"
              value={dateTo}
              onChange={(e) => onDateToChange(e.target.value)}
            />
          </div>
        </ATMCard>

        {/* Table Container Card */}
        <ATMCard padding="none" className="shadow-sm border border-gray-100 dark:border-gray-800 overflow-hidden rounded-2xl">
          <ATMTable
            columns={columns}
            data={tokens}
            isLoading={isLoading}
            isFetching={isFetching}
            rowActions={rowActions}
            density="compact"
            emptyMessage="No tokens found. Generate your first token to get started."
            extraHeaderActions={
              <ATMButton
                type="button"
                variant="outline"
                size="sm"
                icon={Download}
                onClick={onExportCsv}
                className="hover:scale-[1.01] transition-transform"
              >
                Export CSV
              </ATMButton>
            }
            pagination={{
              page,
              pageSize,
              totalCount,
              onPageChange,
              onPageSizeChange,
            }}
          />
        </ATMCard>
      </div>

      {/* Revoke Modal */}
      <ATMModal
        isOpen={revokeTarget !== null}
        onClose={() => {
          onRevokeTargetChange(null);
          onRevokeReasonChange('');
        }}
        title="Revoke Token"
        subtitle={`This will permanently revoke the token for ${revokeTarget?.merchantName ?? 'this merchant'}. This action cannot be undone.`}
        size="md"
      >
        <div className="space-y-4">
          <ATMTextField
            name="revokeReason"
            label="Reason for revocation"
            placeholder="e.g. Merchant requested cancellation"
            value={revokeReason}
            onChange={(e) => onRevokeReasonChange(e.target.value)}
          />
          <div className="flex justify-end gap-2 pt-3 border-t border-gray-100 dark:border-gray-800">
            <ATMButton
              type="button"
              variant="secondary"
              size="sm"
              onClick={() => {
                onRevokeTargetChange(null);
                onRevokeReasonChange('');
              }}
            >
              Cancel
            </ATMButton>
            <ATMButton
              type="button"
              variant="danger"
              size="sm"
              onClick={onRevoke}
              isLoading={isRevoking}
              disabled={!revokeReason.trim()}
            >
              Revoke Token
            </ATMButton>
          </div>
        </div>
      </ATMModal>
    </div>
  );
};

export default TokenList;
