import React, { useState, useMemo, useCallback } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { toast } from 'sonner';
import { ROUTES } from '@/lib/config/routes';
import { useToken, useRevokeToken } from '../services/useTokens';
import { TokenView, TimelineEvent } from './TokenView';

function getDaysRemaining(validTo: string): number {
  const now = new Date();
  const expiry = new Date(validTo);
  return Math.max(0, Math.ceil((expiry.getTime() - now.getTime()) / (1000 * 60 * 60 * 24)));
}

export const TokenViewWrapper: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const [copied, setCopied] = useState(false);
  const [revokeModal, setRevokeModal] = useState(false);
  const [revokeReason, setRevokeReason] = useState('');

  const { data, isLoading, isError, refetch } = useToken(id);
  const revokeMutation = useRevokeToken();

  const token = data?.data;

  const daysRemaining = useMemo(() => (token ? getDaysRemaining(token.validTo) : 0), [token]);
  const expiryPercent = useMemo(
    () =>
      token && token.validityDays > 0
        ? Math.min(100, Math.round((daysRemaining / token.validityDays) * 100))
        : 0,
    [daysRemaining, token],
  );

  const timeline = useMemo<TimelineEvent[]>(() => {
    if (!token) return [];
    const events: TimelineEvent[] = [
      {
        id: 'gen',
        timestamp: token.generatedAt,
        title: 'Token Generated',
        description: `Token generated by ${token.generatedBy} for ${token.merchantName}`,
        user: token.generatedBy,
        type: 'success',
      },
      {
        id: 'valid-from',
        timestamp: token.validFrom,
        title: 'Validity Started',
        description: `${token.validityDays}-day validity began`,
        user: 'System',
        type: 'info',
      },
      {
        id: 'expiry',
        timestamp: token.validTo,
        title: token.status === 'Expired' ? 'Token Expired' : 'Token Expiry',
        description:
          token.status === 'Expired'
            ? 'Token expired and is no longer usable'
            : `Token will expire (${token.validityDays}-day validity)`,
        user: 'System',
        type: token.status === 'Expired' ? 'error' : 'warning',
      },
    ];
    if (token.status === 'Revoked') {
      events.push({
        id: 'revoked',
        timestamp: token.validTo,
        title: 'Token Revoked',
        description: 'Token was revoked by an administrator',
        user: 'System',
        type: 'error',
      });
    }
    return events;
  }, [token]);

  const handleCopy = useCallback(() => {
    if (!token) return;
    navigator.clipboard.writeText(token.tokenString).then(
      () => {
        setCopied(true);
        toast.success('Token copied to clipboard');
        setTimeout(() => setCopied(false), 2000);
      },
      () => toast.error('Failed to copy token')
    );
  }, [token]);

  const handleEmail = useCallback(() => {
    if (!token) return;
    toast.info(`Sending token to ${token.merchantName}...`);
  }, [token]);

  const handleRevoke = useCallback(() => {
    if (!revokeReason.trim() || !token) return;
    revokeMutation.mutate(
      { tokenId: token.id, reason: revokeReason },
      {
        onSuccess: () => {
          toast.success('Token revoked successfully');
          setRevokeModal(false);
          setRevokeReason('');
        },
        onError: (err) => {
          toast.error(err instanceof Error ? err.message : 'Failed to revoke token');
        },
      },
    );
  }, [revokeReason, token, revokeMutation]);

  const handleBack = useCallback(() => {
    navigate(ROUTES.TOKENS.LIST);
  }, [navigate]);

  return (
    <TokenView
      token={token}
      isLoading={isLoading}
      isError={isError}
      refetch={refetch}
      daysRemaining={daysRemaining}
      expiryPercent={expiryPercent}
      copied={copied}
      handleCopy={handleCopy}
      handleEmail={handleEmail}
      revokeModal={revokeModal}
      setRevokeModal={setRevokeModal}
      revokeReason={revokeReason}
      setRevokeReason={setRevokeReason}
      handleRevoke={handleRevoke}
      isRevoking={revokeMutation.isPending}
      timeline={timeline}
      onBack={handleBack}
    />
  );
};

export default TokenViewWrapper;
